name: MYTEST

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    name: "Test output"
    runs-on: ubuntu-latest
    steps:
      - name: test-output-1
        id: params
        run: |
          WORK_VER=123
          echo "G_WORK_VER=$WORK_VER" >> $GITHUB_OUTPUT
      - name: test-output-2
        run: |
          echo $G_WORK_VER
        env:
          G_WORK_VER: ${{steps.params.outputs.G_WORK_VER}}
      - name: test-output-3
        run: |
          WORK_VER_ECHO=12345
          echo "WORK_VER_ECHO=$(echo $WORK_VER_ECHO)" >> $GITHUB_ENV
      - name: test-output-4
        run: |
          echo $WORK_VER_ECHO
